**********************************************************************
*** Teaching directory for 										   ***
*** Codes for Ahlfeldt & Barr (2022): The economics of skyscrapers ***											
*** (c) Gabriel M Ahlfeldt, 01/2024								   ***
**********************************************************************

*** This do file uses the programmes to solve the model under the baseline parametrization
*** and illustrate the spatial structure of the stylized city

*** It is straightforward to solve to conduct comparative statics by changing 
*** solving the model under alternative values of parameters and fundamentals and
*** compare the equilibrium outcomes

*** Most of the figures in the paper can be generated by solving the model under 
*** varying values of parameters and exogenous characteristics and analysing the 
*** endogenous outomes

// First load sythetic data set
u "DATA\SIMULATION\BASE.dta", clear

// Baseline gradients
// Syntax 	theta_C	theta_R	omega_C	omega_R	beta_C	a_bar_C	a_bar_R	tau_C	tau_R	c_C		c_R 	r_a 	S_bar_C	S_bar_R
FINDEQ 		0.5 	0.55 	0.03 	0.07 	0.030 	2		1 		0.01 	0.005 	1.3 	1.3 	50		999		999

GBIDRENT name1
GHEIGHT name0
GLANDRENT name3
grc1leg name1 name0 name3, cols(3) leg(name3) xsize(10) ysize(5)
	graph export "FIGS\FIG_gradients.pdf", replace
	graph export "FIGS\FIG_gradients.png", width(2400) height(1200) replace 

	
	
	
	
/*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

		Begin of student written solutions to tutorial 3


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/	
	
	
	
	
	
	
	
	
* Task 1 
	
********************************
*** Introduce a height limit ***		
********************************
	
// Syntax 	theta_C	theta_R	omega_C	omega_R	beta_C	a_bar_C	a_bar_R	tau_C	tau_R	c_C		c_R 	r_a 	S_bar_C	S_bar_R
FINDEQ 		0.5 	0.55 	0.03 	0.07 	0.030 	2		1 		0.01 	0.005 	1.3 	1.3 	50		20		20
GBIDRENT name1
GHEIGHT name0
GLANDRENT name3
grc1leg name1 name0 name3, cols(3) leg(name3) xsize(10) ysize(5)
	graph export "FIGS\FIG_gradients_wHL.pdf", replace
	graph export "FIGS\FIG_gradients_wHL.png", width(2400) height(1200) replace 
	
*** Notice how the height limit not only affects building heights, but also the level	
*** of price gradients, the land bid rents, the horizontal land use pattern and, 
*** importantly, city size and wage



** Task 2


********************************
*** Replicate Figure 15 ***		
********************************


forvalues theta_c = 0.4(0.01)0.61 {
	u "DATA\SIMULATION\BASE.dta", clear
	
	if (`theta_c' == 0.4) local first = 1
	if (`theta_c' != 0.4) local first = 0
	
	scalar theta_r = `theta_c' + 0.05
	
	// Syntax 	theta_C	theta_R		omega_C	omega_R	beta_C	a_bar_C	a_bar_R	tau_C	tau_R	c_C		c_R 	r_a 	S_bar_C	S_bar_R
	FINDEQ 		`theta_c' theta_r 	0.03 	0.07 	0.030 	2		1 		0.01 	0.005 	1.3 	1.3 	50		999 	999
	
	gen theta_c = `theta_c'

	foreach var in p_bar_x_C p_bar_x_R S_x_C S_x_R {
		egen `var'_max = max(`var')
	}
	egen x_0 = max(x) if COM == 1 
	egen x_1 = max(x) if COM == 0 & URBAN == 1
	
* Total floor space in the city, the 0.1 is the discrete steps in distance from CBD 

	gen fl_space_c = 0.01 * S_x_C if COM == 1 
	egen tot_fl_space_c = total(fl_space_c)
	
	gen fl_space_r = 0.01 * S_x_R if COM == 0 & URBAN == 1
	egen tot_fl_space_r = total(fl_space_r)	
	
	gen fl_space_tot = tot_fl_space_c + tot_fl_space_r
	
	egen p_bar_x_C_mean = mean(p_bar_x_C)
	egen p_bar_x_R_mean = mean(p_bar_x_R)
	
	

	* collapse (mean) theta_c L y p_bar_x_C_max p_bar_x_R_max S_x_C_max S_x_R_max x_0 x_1 fl_space_tot tot_fl_space_r tot_fl_space_c 
	
	if `first' == 1 {
		save "DATA\SIMULATION\fig_15.dta", replace
		local first = 0
	}
	else {
		append using "DATA\SIMULATION\fig_15.dta"
		save "DATA\SIMULATION\fig_15.dta", replace
	}
}


/*
Assumption: Linear City 
one unit of land at each location x 

Height of building = floor space supplied at that location 

Integrate over the sum of floor space over all locations that constitue the city 

*/







	

** Plot Results
graph drop _all
use "DATA\SIMULATION\fig_15.dta", clear

replace L = L / 1000000

twoway (line L theta_c, lcolor(black) lpattern(dash)), ///
    xtitle("Height elasticity of construction cost") ///
    ytitle("Population (millions)") ///
	name(graph_01)
	

twoway (line x_0 theta_c, lcolor(red) lpattern(dash) ///
         legend(label(1 "Commercial"))) /// 
       (line x_1 theta_c, lcolor(blue) lpattern(dash) ///
         legend(label(2 "Residential"))), ///
    xtitle("Height elasticity of construction cost") /// 
    ytitle("Outer zone boundary (distance)") /// 
    legend(rows(1)) name(graph_02)

	
twoway (line S_x_C_max theta_c, lcolor(red) lpattern(dash)) ///
       (line S_x_R_max theta_c, lcolor(blue) lpattern(dash)), ///
    xtitle("Height elasticity of construction cost") ///
    ytitle("Height of talles building (floors)") /// 
	name(graph_03)	
	
twoway (line y L, lcolor(black) lpattern(dash)), ///
    ytitle("Wage index") ///
    xtitle("Population (millions)") ///
	name(graph_04)
	
twoway (line p_bar_x_C_max L, lcolor(red) lpattern(dash)) ///
       (line p_bar_x_R_max L, lcolor(blue) lpattern(dash)), ///
    xtitle("Population in millions") ///
    ytitle("Maximum floor space rent") /// 
	name(graph_05)	

twoway (line S_x_C_max L, lcolor(red) lpattern(dash)) ///
       (line S_x_R_max L, lcolor(blue) lpattern(dash)), ///
    xtitle("Population in millions") ///
    ytitle("Height of tallest building") /// 
	name(graph_06)	


grc1leg graph_01 graph_02 graph_03 graph_04 graph_05 graph_06, cols(3) leg(graph_02) xsize(10) ysize(5) 


	graph export "FIGS\recreated_fig15.png", width(2400) height(1200) replace 


	
	
* Taks 3 Floor Space, supply elasticity -- here one observation is one city 
********************************
*** Floor space elasticities ***		
********************************	

use "DATA\SIMULATION\fig_15.dta", clear

* put in logs
	foreach var in p_bar_x_C_max p_bar_x_R_max tot_fl_space_r tot_fl_space_c p_bar_x_C_mean p_bar_x_R_mean p_bar_x_C p_bar_x_R {
		gen `var'_l = log(`var')
	}

	
* This uses maximum floor price rents	
	reg tot_fl_space_r_l p_bar_x_R_max_l

	reg tot_fl_space_c_l p_bar_x_C_max_l

* This uses entire data of the city
* Elasticity for commercial district is very high
* Elasticity for residential district is negative? -- bc higher rents adjust so that workers leave city which would yield less land supply -> indirect channel
	reg tot_fl_space_r_l p_bar_x_R_l
	
	reg tot_fl_space_c_l p_bar_x_C_l
	
	
	
	
* Task 4 	
********************************
*** Population sizes ***		
********************************
	
* a)
* Change pop size by changing a_bar_c 

forvalues a_bar_c = 2(0.1)4 {
	u "DATA\SIMULATION\BASE.dta", clear
	
	if (`a_bar_c' == 2) local first = 1
	if (`a_bar_c' != 2) local first = 0
	
	
	// Syntax 	theta_C		theta_R	omega_C	omega_R	beta_C	a_bar_C		a_bar_R		tau_C	tau_R	c_C		c_R 	r_a S_bar_C		S_bar_R
	FINDEQ 		0.5 		0.55 	0.03 	0.07 	0.030 	`a_bar_c'		1 		0.01 	0.005 	1.3 	1.3 	50		999 	999
	
	gen a_bar_c = `a_bar_c'

	collapse (mean) y L a_bar_c
	
	if `first' == 1 {
		save "DATA\SIMULATION\task_4_a.dta", replace
		local first = 0
	}
	else {
		append using "DATA\SIMULATION\task_4_a.dta"
		save "DATA\SIMULATION\task_4_a.dta", replace
	}
}
	
	
use "DATA\SIMULATION\task_4_a.dta", clear
	
	
	foreach var in L y {
		gen `var'_l = log(`var')
	}
	
	
	reg y_l L_l
	* this is a lot larger than the beta. We probably would have to net out with the residential effects 
	
	
	
* b)
* Change pop size by changing a_bar_r 
* --- fundamentally this is a dispersion force and therefore counteract the agglomeration effects

forvalues a_bar_r = 1(0.1)3 {
	u "DATA\SIMULATION\BASE.dta", clear
	
	if (`a_bar_r' == 1) local first = 1
	if (`a_bar_r' != 1) local first = 0
	
	
	// Syntax 	theta_C		theta_R	omega_C	omega_R	beta_C	a_bar_C		a_bar_R		tau_C	tau_R	c_C		c_R 	r_a S_bar_C		S_bar_R
	FINDEQ 		0.5 		0.55 	0.03 	0.07 	0.030 	2		 `a_bar_r' 		0.01 	0.005 	1.3 	1.3 	50		999 	999
	
	gen a_bar_r = `a_bar_r'

	collapse (mean) y L a_bar_r
	
	if `first' == 1 {
		save "DATA\SIMULATION\task_4_b.dta", replace
		local first = 0
	}
	else {
		append using "DATA\SIMULATION\task_4_b.dta"
		save "DATA\SIMULATION\task_4_b.dta", replace
	}
}
	
	
use "DATA\SIMULATION\task_4_b.dta", clear
	
	
	foreach var in L y {
		gen `var'_l = log(`var')
	}
	
	
	reg y_l L_l
	
	
	
* c) 
/*
Typically just uses log of density on log of productivity using observational data
- Endogeneity
	- Density is correlated with factors that also affect productivity
	- e.g. sorting of high skilled into cities
	- reverse causality

- Effect is net, combo of agglomeration economies positive of productivity as well as dispersion forces, e.g. congestion

- 


*/


	
	
	
	
	
	
	
	
	
	
	
	
**************************************
*** Do file successfully completed ***	
**************************************	